-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL AND FOLLOWS STRICT RULES
-- In other words, I ain't writing a lua parser for this, so please be a good boi/girl/whatever

--hl.config({ decoration = { rounding = 22 } })
hl.config({ decoration = { blur = { enabled = true } } })
hl.config({ decoration = { blur = { size = 6 } } })
hl.config({ decoration = { blur = { passes = 2 } } })
hl.config({ decoration = { active_opacity = 0.88 } })
hl.config({ decoration = { inactive_opacity = 0.78 } })
